import Head from 'next/head'
import Image from 'next/image'
import ValorantIcon from '../public/Logo valorant.svg'
import ShareIcon from '../public/share-2.svg'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Valorant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <header className={styles.header}>
      <nav className={`${styles.nav} ${styles.containerArea}`}>
        <Image src={ValorantIcon} alt='logo' width='58.1px' height='39.49px'/>
        <h1 className={styles.title}>Riot Games</h1>
        <Image src={ShareIcon} alt='share' width={24} height={24}/>
      </nav>
    </header>
    </div>
  )
}
